### PR TITLE
Remove use of Stopwatch

### PR DESCRIPTION
**Pull request by dump247**
This makes ostrich compatible with versions of guava back to 14.

### CODE REVIEW

**Comment by dump247** [comment]
This is an alternative to #176

**Comment by ohhatiya** [comment]
:metal:

**Comment by dump247** [comment]
@ohhatiya what do you think of this vs #176?

**Comment by ohhatiya** [comment]
Having a StopWatch type class might be useful if we use that functionality multiple places, but since it's only really used one place I think I like this better for now.

**Pull request merged**
